// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nitric/proto/resources/v1/resources.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nitric.Proto.Resources.v1 {
  /// <summary>
  /// Nitric Resource Service
  /// The service definition exists to allow a nitric application to declare peripheral dependencies
  /// </summary>
  public static partial class Resources
  {
    static readonly string __ServiceName = "nitric.proto.resources.v1.Resources";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Nitric.Proto.Resources.v1.ResourceDeclareRequest> __Marshaller_nitric_proto_resources_v1_ResourceDeclareRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Resources.v1.ResourceDeclareRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.Resources.v1.ResourceDeclareResponse> __Marshaller_nitric_proto_resources_v1_ResourceDeclareResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Resources.v1.ResourceDeclareResponse.Parser));

    static readonly grpc::Method<global::Nitric.Proto.Resources.v1.ResourceDeclareRequest, global::Nitric.Proto.Resources.v1.ResourceDeclareResponse> __Method_Declare = new grpc::Method<global::Nitric.Proto.Resources.v1.ResourceDeclareRequest, global::Nitric.Proto.Resources.v1.ResourceDeclareResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Declare",
        __Marshaller_nitric_proto_resources_v1_ResourceDeclareRequest,
        __Marshaller_nitric_proto_resources_v1_ResourceDeclareResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nitric.Proto.Resources.v1.ResourcesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Resources</summary>
    [grpc::BindServiceMethod(typeof(Resources), "BindService")]
    public abstract partial class ResourcesBase
    {
      /// <summary>
      /// Declare a resource for the nitric application
      /// At Deploy time this will create resources as part of the nitric stacks dependency graph
      /// At runtime
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.Resources.v1.ResourceDeclareResponse> Declare(global::Nitric.Proto.Resources.v1.ResourceDeclareRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Resources</summary>
    public partial class ResourcesClient : grpc::ClientBase<ResourcesClient>
    {
      /// <summary>Creates a new client for Resources</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ResourcesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Resources that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ResourcesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ResourcesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ResourcesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Declare a resource for the nitric application
      /// At Deploy time this will create resources as part of the nitric stacks dependency graph
      /// At runtime
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Resources.v1.ResourceDeclareResponse Declare(global::Nitric.Proto.Resources.v1.ResourceDeclareRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Declare(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Declare a resource for the nitric application
      /// At Deploy time this will create resources as part of the nitric stacks dependency graph
      /// At runtime
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Resources.v1.ResourceDeclareResponse Declare(global::Nitric.Proto.Resources.v1.ResourceDeclareRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Declare, null, options, request);
      }
      /// <summary>
      /// Declare a resource for the nitric application
      /// At Deploy time this will create resources as part of the nitric stacks dependency graph
      /// At runtime
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Resources.v1.ResourceDeclareResponse> DeclareAsync(global::Nitric.Proto.Resources.v1.ResourceDeclareRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeclareAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Declare a resource for the nitric application
      /// At Deploy time this will create resources as part of the nitric stacks dependency graph
      /// At runtime
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Resources.v1.ResourceDeclareResponse> DeclareAsync(global::Nitric.Proto.Resources.v1.ResourceDeclareRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Declare, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ResourcesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ResourcesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ResourcesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Declare, serviceImpl.Declare).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ResourcesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Declare, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.Resources.v1.ResourceDeclareRequest, global::Nitric.Proto.Resources.v1.ResourceDeclareResponse>(serviceImpl.Declare));
    }

  }
}
#endregion
