name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  version bump:
    runs-on: ubuntu-latest
    
    steps:
      - name: Version Bump
        run: |
          versionize -w ./Nitric.Proto
          versionize -w ./Nitric.Sdk
        shell: bash

  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: 5.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Exclude Test Project
      run: dotnet sln remove Nitric.Test/**
    - name: Restore Dependencies
      run: dotnet restore
    - name: Publish
      run: |
        mkdir __out
        dotnet pack -c Release -o __out --no-restore
        dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}}
        rm -rf __out
    
