// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nitric/proto/keyvalue/v1/keyvalue.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nitric.Proto.KeyValue.v1 {
  /// <summary>
  /// Service for storage and retrieval of simple JSON keyValue
  /// </summary>
  public static partial class KeyValue
  {
    static readonly string __ServiceName = "nitric.proto.KeyValue.v1.KeyValue";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest> __Marshaller_nitric_proto_KeyValue_v1_KeyValueGetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse> __Marshaller_nitric_proto_KeyValue_v1_KeyValueGetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest> __Marshaller_nitric_proto_KeyValue_v1_KeyValueSetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse> __Marshaller_nitric_proto_KeyValue_v1_KeyValueSetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest> __Marshaller_nitric_proto_KeyValue_v1_KeyValueDeleteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse> __Marshaller_nitric_proto_KeyValue_v1_KeyValueDeleteResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse.Parser));

    static readonly grpc::Method<global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest, global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse> __Method_Get = new grpc::Method<global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest, global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_nitric_proto_KeyValue_v1_KeyValueGetRequest,
        __Marshaller_nitric_proto_KeyValue_v1_KeyValueGetResponse);

    static readonly grpc::Method<global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest, global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse> __Method_Set = new grpc::Method<global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest, global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Set",
        __Marshaller_nitric_proto_KeyValue_v1_KeyValueSetRequest,
        __Marshaller_nitric_proto_KeyValue_v1_KeyValueSetResponse);

    static readonly grpc::Method<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest, global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse> __Method_Delete = new grpc::Method<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest, global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_nitric_proto_KeyValue_v1_KeyValueDeleteRequest,
        __Marshaller_nitric_proto_KeyValue_v1_KeyValueDeleteResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nitric.Proto.KeyValue.v1.KeyvalueReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of KeyValue</summary>
    [grpc::BindServiceMethod(typeof(KeyValue), "BindService")]
    public abstract partial class KeyValueBase
    {
      /// <summary>
      /// Get an existing document
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse> Get(global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Create a new or overwrite an existing document
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse> Set(global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Delete an existing document
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse> Delete(global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for KeyValue</summary>
    public partial class KeyValueClient : grpc::ClientBase<KeyValueClient>
    {
      /// <summary>Creates a new client for KeyValue</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public KeyValueClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for KeyValue that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public KeyValueClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected KeyValueClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected KeyValueClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Get an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse Get(global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse Get(global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      /// <summary>
      /// Get an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse> GetAsync(global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse> GetAsync(global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      /// <summary>
      /// Create a new or overwrite an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse Set(global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Set(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a new or overwrite an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse Set(global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Set, null, options, request);
      }
      /// <summary>
      /// Create a new or overwrite an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse> SetAsync(global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a new or overwrite an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse> SetAsync(global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Set, null, options, request);
      }
      /// <summary>
      /// Delete an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse Delete(global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse Delete(global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>
      /// Delete an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse> DeleteAsync(global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete an existing document
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse> DeleteAsync(global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override KeyValueClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new KeyValueClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(KeyValueBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Set, serviceImpl.Set)
          .AddMethod(__Method_Delete, serviceImpl.Delete).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, KeyValueBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.KeyValue.v1.KeyValueGetRequest, global::Nitric.Proto.KeyValue.v1.KeyValueGetResponse>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_Set, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.KeyValue.v1.KeyValueSetRequest, global::Nitric.Proto.KeyValue.v1.KeyValueSetResponse>(serviceImpl.Set));
      serviceBinder.AddMethod(__Method_Delete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.KeyValue.v1.KeyValueDeleteRequest, global::Nitric.Proto.KeyValue.v1.KeyValueDeleteResponse>(serviceImpl.Delete));
    }

  }
}
#endregion
