// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/resource/v1/resource.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nitric.Proto.Resource.v1 {

  /// <summary>Holder for reflection information generated from proto/resource/v1/resource.proto</summary>
  public static partial class ResourceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/resource/v1/resource.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBwcm90by9yZXNvdXJjZS92MS9yZXNvdXJjZS5wcm90bxISbml0cmljLnJl",
            "c291cmNlLnYxGhd2YWxpZGF0ZS92YWxpZGF0ZS5wcm90byKgAQoOUG9saWN5",
            "UmVzb3VyY2USMAoKcHJpbmNpcGFscxgBIAMoCzIcLm5pdHJpYy5yZXNvdXJj",
            "ZS52MS5SZXNvdXJjZRIrCgdhY3Rpb25zGAIgAygOMhoubml0cmljLnJlc291",
            "cmNlLnYxLkFjdGlvbhIvCglyZXNvdXJjZXMYAyADKAsyHC5uaXRyaWMucmVz",
            "b3VyY2UudjEuUmVzb3VyY2UiSAoIUmVzb3VyY2USLgoEdHlwZRgBIAEoDjIg",
            "Lm5pdHJpYy5yZXNvdXJjZS52MS5SZXNvdXJjZVR5cGUSDAoEbmFtZRgCIAEo",
            "CSLKAwoWUmVzb3VyY2VEZWNsYXJlUmVxdWVzdBIuCghyZXNvdXJjZRgBIAEo",
            "CzIcLm5pdHJpYy5yZXNvdXJjZS52MS5SZXNvdXJjZRI0CgZwb2xpY3kYCiAB",
            "KAsyIi5uaXRyaWMucmVzb3VyY2UudjEuUG9saWN5UmVzb3VyY2VIABI0CgZi",
            "dWNrZXQYCyABKAsyIi5uaXRyaWMucmVzb3VyY2UudjEuQnVja2V0UmVzb3Vy",
            "Y2VIABIyCgVxdWV1ZRgMIAEoCzIhLm5pdHJpYy5yZXNvdXJjZS52MS5RdWV1",
            "ZVJlc291cmNlSAASMgoFdG9waWMYDSABKAsyIS5uaXRyaWMucmVzb3VyY2Uu",
            "djEuVG9waWNSZXNvdXJjZUgAEjwKCmNvbGxlY3Rpb24YDiABKAsyJi5uaXRy",
            "aWMucmVzb3VyY2UudjEuQ29sbGVjdGlvblJlc291cmNlSAASNAoGc2VjcmV0",
            "GA8gASgLMiIubml0cmljLnJlc291cmNlLnYxLlNlY3JldFJlc291cmNlSAAS",
            "LgoDYXBpGBAgASgLMh8ubml0cmljLnJlc291cmNlLnYxLkFwaVJlc291cmNl",
            "SABCCAoGY29uZmlnIhAKDkJ1Y2tldFJlc291cmNlIg8KDVF1ZXVlUmVzb3Vy",
            "Y2UiDwoNVG9waWNSZXNvdXJjZSIUChJDb2xsZWN0aW9uUmVzb3VyY2UiEAoO",
            "U2VjcmV0UmVzb3VyY2UiPQoYQXBpU2VjdXJpdHlEZWZpbml0aW9uSnd0Eg4K",
            "Bmlzc3VlchgBIAEoCRIRCglhdWRpZW5jZXMYAiADKAkiYgoVQXBpU2VjdXJp",
            "dHlEZWZpbml0aW9uEjsKA2p3dBgBIAEoCzIsLm5pdHJpYy5yZXNvdXJjZS52",
            "MS5BcGlTZWN1cml0eURlZmluaXRpb25Kd3RIAEIMCgpkZWZpbml0aW9uIhsK",
            "CUFwaVNjb3BlcxIOCgZzY29wZXMYASADKAki3QIKC0FwaVJlc291cmNlElYK",
            "FHNlY3VyaXR5X2RlZmluaXRpb25zGAEgAygLMjgubml0cmljLnJlc291cmNl",
            "LnYxLkFwaVJlc291cmNlLlNlY3VyaXR5RGVmaW5pdGlvbnNFbnRyeRI/Cghz",
            "ZWN1cml0eRgCIAMoCzItLm5pdHJpYy5yZXNvdXJjZS52MS5BcGlSZXNvdXJj",
            "ZS5TZWN1cml0eUVudHJ5GmUKGFNlY3VyaXR5RGVmaW5pdGlvbnNFbnRyeRIL",
            "CgNrZXkYASABKAkSOAoFdmFsdWUYAiABKAsyKS5uaXRyaWMucmVzb3VyY2Uu",
            "djEuQXBpU2VjdXJpdHlEZWZpbml0aW9uOgI4ARpOCg1TZWN1cml0eUVudHJ5",
            "EgsKA2tleRgBIAEoCRIsCgV2YWx1ZRgCIAEoCzIdLm5pdHJpYy5yZXNvdXJj",
            "ZS52MS5BcGlTY29wZXM6AjgBIhkKF1Jlc291cmNlRGVjbGFyZVJlc3BvbnNl",
            "Ko8BCgxSZXNvdXJjZVR5cGUSBwoDQXBpEAASDAoIRnVuY3Rpb24QARIKCgZC",
            "dWNrZXQQAhIJCgVRdWV1ZRADEgkKBVRvcGljEAQSDAoIU2NoZWR1bGUQBRIQ",
            "CgxTdWJzY3JpcHRpb24QBhIOCgpDb2xsZWN0aW9uEAcSCgoGUG9saWN5EAgS",
            "CgoGU2VjcmV0EAkq/wIKBkFjdGlvbhISCg5CdWNrZXRGaWxlTGlzdBAAEhEK",
            "DUJ1Y2tldEZpbGVHZXQQARIRCg1CdWNrZXRGaWxlUHV0EAISFAoQQnVja2V0",
            "RmlsZURlbGV0ZRADEg4KCVRvcGljTGlzdBDIARIQCgtUb3BpY0RldGFpbBDJ",
            "ARIWChFUb3BpY0V2ZW50UHVibGlzaBDKARIOCglRdWV1ZVNlbmQQrAISEQoM",
            "UXVldWVSZWNlaXZlEK0CEg4KCVF1ZXVlTGlzdBCuAhIQCgtRdWV1ZURldGFp",
            "bBCvAhIbChZDb2xsZWN0aW9uRG9jdW1lbnRSZWFkEJADEhwKF0NvbGxlY3Rp",
            "b25Eb2N1bWVudFdyaXRlEJEDEh0KGENvbGxlY3Rpb25Eb2N1bWVudERlbGV0",
            "ZRCSAxIUCg9Db2xsZWN0aW9uUXVlcnkQkwMSEwoOQ29sbGVjdGlvbkxpc3QQ",
            "lAMSDgoJU2VjcmV0UHV0EPQDEhEKDFNlY3JldEFjY2VzcxD1AzJ1Cg9SZXNv",
            "dXJjZVNlcnZpY2USYgoHRGVjbGFyZRIqLm5pdHJpYy5yZXNvdXJjZS52MS5S",
            "ZXNvdXJjZURlY2xhcmVSZXF1ZXN0Gisubml0cmljLnJlc291cmNlLnYxLlJl",
            "c291cmNlRGVjbGFyZVJlc3BvbnNlQm4KG2lvLm5pdHJpYy5wcm90by5yZXNv",
            "dXJjZS52MUIJUmVzb3VyY2VzUAFaDG5pdHJpYy92MTt2MaoCGE5pdHJpYy5Q",
            "cm90by5SZXNvdXJjZS52McoCGE5pdHJpY1xQcm90b1xSZXNvdXJjZVxWMWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Nitric.Proto.Resource.v1.ResourceType), typeof(global::Nitric.Proto.Resource.v1.Action), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.PolicyResource), global::Nitric.Proto.Resource.v1.PolicyResource.Parser, new[]{ "Principals", "Actions", "Resources" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.Resource), global::Nitric.Proto.Resource.v1.Resource.Parser, new[]{ "Type", "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.ResourceDeclareRequest), global::Nitric.Proto.Resource.v1.ResourceDeclareRequest.Parser, new[]{ "Resource", "Policy", "Bucket", "Queue", "Topic", "Collection", "Secret", "Api" }, new[]{ "Config" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.BucketResource), global::Nitric.Proto.Resource.v1.BucketResource.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.QueueResource), global::Nitric.Proto.Resource.v1.QueueResource.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.TopicResource), global::Nitric.Proto.Resource.v1.TopicResource.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.CollectionResource), global::Nitric.Proto.Resource.v1.CollectionResource.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.SecretResource), global::Nitric.Proto.Resource.v1.SecretResource.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt), global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt.Parser, new[]{ "Issuer", "Audiences" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.ApiSecurityDefinition), global::Nitric.Proto.Resource.v1.ApiSecurityDefinition.Parser, new[]{ "Jwt" }, new[]{ "Definition" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.ApiScopes), global::Nitric.Proto.Resource.v1.ApiScopes.Parser, new[]{ "Scopes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.ApiResource), global::Nitric.Proto.Resource.v1.ApiResource.Parser, new[]{ "SecurityDefinitions", "Security" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Nitric.Proto.Resource.v1.ResourceDeclareResponse), global::Nitric.Proto.Resource.v1.ResourceDeclareResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ResourceType {
    [pbr::OriginalName("Api")] Api = 0,
    [pbr::OriginalName("Function")] Function = 1,
    [pbr::OriginalName("Bucket")] Bucket = 2,
    [pbr::OriginalName("Queue")] Queue = 3,
    [pbr::OriginalName("Topic")] Topic = 4,
    [pbr::OriginalName("Schedule")] Schedule = 5,
    [pbr::OriginalName("Subscription")] Subscription = 6,
    [pbr::OriginalName("Collection")] Collection = 7,
    [pbr::OriginalName("Policy")] Policy = 8,
    [pbr::OriginalName("Secret")] Secret = 9,
  }

  public enum Action {
    /// <summary>
    /// Bucket Permissions: 0XX
    /// </summary>
    [pbr::OriginalName("BucketFileList")] BucketFileList = 0,
    [pbr::OriginalName("BucketFileGet")] BucketFileGet = 1,
    [pbr::OriginalName("BucketFilePut")] BucketFilePut = 2,
    [pbr::OriginalName("BucketFileDelete")] BucketFileDelete = 3,
    /// <summary>
    /// Topic Permissions: 2XX
    /// </summary>
    [pbr::OriginalName("TopicList")] TopicList = 200,
    [pbr::OriginalName("TopicDetail")] TopicDetail = 201,
    [pbr::OriginalName("TopicEventPublish")] TopicEventPublish = 202,
    /// <summary>
    /// Queue Permissions: 3XX
    /// </summary>
    [pbr::OriginalName("QueueSend")] QueueSend = 300,
    [pbr::OriginalName("QueueReceive")] QueueReceive = 301,
    [pbr::OriginalName("QueueList")] QueueList = 302,
    [pbr::OriginalName("QueueDetail")] QueueDetail = 303,
    /// <summary>
    /// Collection Permissions: 4XX
    /// </summary>
    [pbr::OriginalName("CollectionDocumentRead")] CollectionDocumentRead = 400,
    [pbr::OriginalName("CollectionDocumentWrite")] CollectionDocumentWrite = 401,
    [pbr::OriginalName("CollectionDocumentDelete")] CollectionDocumentDelete = 402,
    [pbr::OriginalName("CollectionQuery")] CollectionQuery = 403,
    [pbr::OriginalName("CollectionList")] CollectionList = 404,
    /// <summary>
    /// Secret Permissions: 5XX
    /// </summary>
    [pbr::OriginalName("SecretPut")] SecretPut = 500,
    [pbr::OriginalName("SecretAccess")] SecretAccess = 501,
  }

  #endregion

  #region Messages
  public sealed partial class PolicyResource : pb::IMessage<PolicyResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PolicyResource> _parser = new pb::MessageParser<PolicyResource>(() => new PolicyResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PolicyResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PolicyResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PolicyResource(PolicyResource other) : this() {
      principals_ = other.principals_.Clone();
      actions_ = other.actions_.Clone();
      resources_ = other.resources_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PolicyResource Clone() {
      return new PolicyResource(this);
    }

    /// <summary>Field number for the "principals" field.</summary>
    public const int PrincipalsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Nitric.Proto.Resource.v1.Resource> _repeated_principals_codec
        = pb::FieldCodec.ForMessage(10, global::Nitric.Proto.Resource.v1.Resource.Parser);
    private readonly pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Resource> principals_ = new pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Resource>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Resource> Principals {
      get { return principals_; }
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Nitric.Proto.Resource.v1.Action> _repeated_actions_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::Nitric.Proto.Resource.v1.Action) x);
    private readonly pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Action> actions_ = new pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Action>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Action> Actions {
      get { return actions_; }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Nitric.Proto.Resource.v1.Resource> _repeated_resources_codec
        = pb::FieldCodec.ForMessage(26, global::Nitric.Proto.Resource.v1.Resource.Parser);
    private readonly pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Resource> resources_ = new pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Resource>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Nitric.Proto.Resource.v1.Resource> Resources {
      get { return resources_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PolicyResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PolicyResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!principals_.Equals(other.principals_)) return false;
      if(!actions_.Equals(other.actions_)) return false;
      if(!resources_.Equals(other.resources_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= principals_.GetHashCode();
      hash ^= actions_.GetHashCode();
      hash ^= resources_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      principals_.WriteTo(output, _repeated_principals_codec);
      actions_.WriteTo(output, _repeated_actions_codec);
      resources_.WriteTo(output, _repeated_resources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      principals_.WriteTo(ref output, _repeated_principals_codec);
      actions_.WriteTo(ref output, _repeated_actions_codec);
      resources_.WriteTo(ref output, _repeated_resources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += principals_.CalculateSize(_repeated_principals_codec);
      size += actions_.CalculateSize(_repeated_actions_codec);
      size += resources_.CalculateSize(_repeated_resources_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PolicyResource other) {
      if (other == null) {
        return;
      }
      principals_.Add(other.principals_);
      actions_.Add(other.actions_);
      resources_.Add(other.resources_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            principals_.AddEntriesFrom(input, _repeated_principals_codec);
            break;
          }
          case 18:
          case 16: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
          case 26: {
            resources_.AddEntriesFrom(input, _repeated_resources_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            principals_.AddEntriesFrom(ref input, _repeated_principals_codec);
            break;
          }
          case 18:
          case 16: {
            actions_.AddEntriesFrom(ref input, _repeated_actions_codec);
            break;
          }
          case 26: {
            resources_.AddEntriesFrom(ref input, _repeated_resources_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Resource : pb::IMessage<Resource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Resource> _parser = new pb::MessageParser<Resource>(() => new Resource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resource(Resource other) : this() {
      type_ = other.type_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resource Clone() {
      return new Resource(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Nitric.Proto.Resource.v1.ResourceType type_ = global::Nitric.Proto.Resource.v1.ResourceType.Api;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.ResourceType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Nitric.Proto.Resource.v1.ResourceType.Api) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Nitric.Proto.Resource.v1.ResourceType.Api) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Nitric.Proto.Resource.v1.ResourceType.Api) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Nitric.Proto.Resource.v1.ResourceType.Api) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resource other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Nitric.Proto.Resource.v1.ResourceType.Api) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Nitric.Proto.Resource.v1.ResourceType) input.ReadEnum();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Nitric.Proto.Resource.v1.ResourceType) input.ReadEnum();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ResourceDeclareRequest : pb::IMessage<ResourceDeclareRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceDeclareRequest> _parser = new pb::MessageParser<ResourceDeclareRequest>(() => new ResourceDeclareRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResourceDeclareRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceDeclareRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceDeclareRequest(ResourceDeclareRequest other) : this() {
      resource_ = other.resource_ != null ? other.resource_.Clone() : null;
      switch (other.ConfigCase) {
        case ConfigOneofCase.Policy:
          Policy = other.Policy.Clone();
          break;
        case ConfigOneofCase.Bucket:
          Bucket = other.Bucket.Clone();
          break;
        case ConfigOneofCase.Queue:
          Queue = other.Queue.Clone();
          break;
        case ConfigOneofCase.Topic:
          Topic = other.Topic.Clone();
          break;
        case ConfigOneofCase.Collection:
          Collection = other.Collection.Clone();
          break;
        case ConfigOneofCase.Secret:
          Secret = other.Secret.Clone();
          break;
        case ConfigOneofCase.Api:
          Api = other.Api.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceDeclareRequest Clone() {
      return new ResourceDeclareRequest(this);
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 1;
    private global::Nitric.Proto.Resource.v1.Resource resource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.Resource Resource {
      get { return resource_; }
      set {
        resource_ = value;
      }
    }

    /// <summary>Field number for the "policy" field.</summary>
    public const int PolicyFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.PolicyResource Policy {
      get { return configCase_ == ConfigOneofCase.Policy ? (global::Nitric.Proto.Resource.v1.PolicyResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Policy;
      }
    }

    /// <summary>Field number for the "bucket" field.</summary>
    public const int BucketFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.BucketResource Bucket {
      get { return configCase_ == ConfigOneofCase.Bucket ? (global::Nitric.Proto.Resource.v1.BucketResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Bucket;
      }
    }

    /// <summary>Field number for the "queue" field.</summary>
    public const int QueueFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.QueueResource Queue {
      get { return configCase_ == ConfigOneofCase.Queue ? (global::Nitric.Proto.Resource.v1.QueueResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Queue;
      }
    }

    /// <summary>Field number for the "topic" field.</summary>
    public const int TopicFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.TopicResource Topic {
      get { return configCase_ == ConfigOneofCase.Topic ? (global::Nitric.Proto.Resource.v1.TopicResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Topic;
      }
    }

    /// <summary>Field number for the "collection" field.</summary>
    public const int CollectionFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.CollectionResource Collection {
      get { return configCase_ == ConfigOneofCase.Collection ? (global::Nitric.Proto.Resource.v1.CollectionResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Collection;
      }
    }

    /// <summary>Field number for the "secret" field.</summary>
    public const int SecretFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.SecretResource Secret {
      get { return configCase_ == ConfigOneofCase.Secret ? (global::Nitric.Proto.Resource.v1.SecretResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Secret;
      }
    }

    /// <summary>Field number for the "api" field.</summary>
    public const int ApiFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.ApiResource Api {
      get { return configCase_ == ConfigOneofCase.Api ? (global::Nitric.Proto.Resource.v1.ApiResource) config_ : null; }
      set {
        config_ = value;
        configCase_ = value == null ? ConfigOneofCase.None : ConfigOneofCase.Api;
      }
    }

    private object config_;
    /// <summary>Enum of possible cases for the "config" oneof.</summary>
    public enum ConfigOneofCase {
      None = 0,
      Policy = 10,
      Bucket = 11,
      Queue = 12,
      Topic = 13,
      Collection = 14,
      Secret = 15,
      Api = 16,
    }
    private ConfigOneofCase configCase_ = ConfigOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigOneofCase ConfigCase {
      get { return configCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearConfig() {
      configCase_ = ConfigOneofCase.None;
      config_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResourceDeclareRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResourceDeclareRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Resource, other.Resource)) return false;
      if (!object.Equals(Policy, other.Policy)) return false;
      if (!object.Equals(Bucket, other.Bucket)) return false;
      if (!object.Equals(Queue, other.Queue)) return false;
      if (!object.Equals(Topic, other.Topic)) return false;
      if (!object.Equals(Collection, other.Collection)) return false;
      if (!object.Equals(Secret, other.Secret)) return false;
      if (!object.Equals(Api, other.Api)) return false;
      if (ConfigCase != other.ConfigCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (resource_ != null) hash ^= Resource.GetHashCode();
      if (configCase_ == ConfigOneofCase.Policy) hash ^= Policy.GetHashCode();
      if (configCase_ == ConfigOneofCase.Bucket) hash ^= Bucket.GetHashCode();
      if (configCase_ == ConfigOneofCase.Queue) hash ^= Queue.GetHashCode();
      if (configCase_ == ConfigOneofCase.Topic) hash ^= Topic.GetHashCode();
      if (configCase_ == ConfigOneofCase.Collection) hash ^= Collection.GetHashCode();
      if (configCase_ == ConfigOneofCase.Secret) hash ^= Secret.GetHashCode();
      if (configCase_ == ConfigOneofCase.Api) hash ^= Api.GetHashCode();
      hash ^= (int) configCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resource_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resource);
      }
      if (configCase_ == ConfigOneofCase.Policy) {
        output.WriteRawTag(82);
        output.WriteMessage(Policy);
      }
      if (configCase_ == ConfigOneofCase.Bucket) {
        output.WriteRawTag(90);
        output.WriteMessage(Bucket);
      }
      if (configCase_ == ConfigOneofCase.Queue) {
        output.WriteRawTag(98);
        output.WriteMessage(Queue);
      }
      if (configCase_ == ConfigOneofCase.Topic) {
        output.WriteRawTag(106);
        output.WriteMessage(Topic);
      }
      if (configCase_ == ConfigOneofCase.Collection) {
        output.WriteRawTag(114);
        output.WriteMessage(Collection);
      }
      if (configCase_ == ConfigOneofCase.Secret) {
        output.WriteRawTag(122);
        output.WriteMessage(Secret);
      }
      if (configCase_ == ConfigOneofCase.Api) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(Api);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resource_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resource);
      }
      if (configCase_ == ConfigOneofCase.Policy) {
        output.WriteRawTag(82);
        output.WriteMessage(Policy);
      }
      if (configCase_ == ConfigOneofCase.Bucket) {
        output.WriteRawTag(90);
        output.WriteMessage(Bucket);
      }
      if (configCase_ == ConfigOneofCase.Queue) {
        output.WriteRawTag(98);
        output.WriteMessage(Queue);
      }
      if (configCase_ == ConfigOneofCase.Topic) {
        output.WriteRawTag(106);
        output.WriteMessage(Topic);
      }
      if (configCase_ == ConfigOneofCase.Collection) {
        output.WriteRawTag(114);
        output.WriteMessage(Collection);
      }
      if (configCase_ == ConfigOneofCase.Secret) {
        output.WriteRawTag(122);
        output.WriteMessage(Secret);
      }
      if (configCase_ == ConfigOneofCase.Api) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(Api);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (resource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resource);
      }
      if (configCase_ == ConfigOneofCase.Policy) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Policy);
      }
      if (configCase_ == ConfigOneofCase.Bucket) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bucket);
      }
      if (configCase_ == ConfigOneofCase.Queue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Queue);
      }
      if (configCase_ == ConfigOneofCase.Topic) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Topic);
      }
      if (configCase_ == ConfigOneofCase.Collection) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Collection);
      }
      if (configCase_ == ConfigOneofCase.Secret) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Secret);
      }
      if (configCase_ == ConfigOneofCase.Api) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Api);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResourceDeclareRequest other) {
      if (other == null) {
        return;
      }
      if (other.resource_ != null) {
        if (resource_ == null) {
          Resource = new global::Nitric.Proto.Resource.v1.Resource();
        }
        Resource.MergeFrom(other.Resource);
      }
      switch (other.ConfigCase) {
        case ConfigOneofCase.Policy:
          if (Policy == null) {
            Policy = new global::Nitric.Proto.Resource.v1.PolicyResource();
          }
          Policy.MergeFrom(other.Policy);
          break;
        case ConfigOneofCase.Bucket:
          if (Bucket == null) {
            Bucket = new global::Nitric.Proto.Resource.v1.BucketResource();
          }
          Bucket.MergeFrom(other.Bucket);
          break;
        case ConfigOneofCase.Queue:
          if (Queue == null) {
            Queue = new global::Nitric.Proto.Resource.v1.QueueResource();
          }
          Queue.MergeFrom(other.Queue);
          break;
        case ConfigOneofCase.Topic:
          if (Topic == null) {
            Topic = new global::Nitric.Proto.Resource.v1.TopicResource();
          }
          Topic.MergeFrom(other.Topic);
          break;
        case ConfigOneofCase.Collection:
          if (Collection == null) {
            Collection = new global::Nitric.Proto.Resource.v1.CollectionResource();
          }
          Collection.MergeFrom(other.Collection);
          break;
        case ConfigOneofCase.Secret:
          if (Secret == null) {
            Secret = new global::Nitric.Proto.Resource.v1.SecretResource();
          }
          Secret.MergeFrom(other.Secret);
          break;
        case ConfigOneofCase.Api:
          if (Api == null) {
            Api = new global::Nitric.Proto.Resource.v1.ApiResource();
          }
          Api.MergeFrom(other.Api);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resource_ == null) {
              Resource = new global::Nitric.Proto.Resource.v1.Resource();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 82: {
            global::Nitric.Proto.Resource.v1.PolicyResource subBuilder = new global::Nitric.Proto.Resource.v1.PolicyResource();
            if (configCase_ == ConfigOneofCase.Policy) {
              subBuilder.MergeFrom(Policy);
            }
            input.ReadMessage(subBuilder);
            Policy = subBuilder;
            break;
          }
          case 90: {
            global::Nitric.Proto.Resource.v1.BucketResource subBuilder = new global::Nitric.Proto.Resource.v1.BucketResource();
            if (configCase_ == ConfigOneofCase.Bucket) {
              subBuilder.MergeFrom(Bucket);
            }
            input.ReadMessage(subBuilder);
            Bucket = subBuilder;
            break;
          }
          case 98: {
            global::Nitric.Proto.Resource.v1.QueueResource subBuilder = new global::Nitric.Proto.Resource.v1.QueueResource();
            if (configCase_ == ConfigOneofCase.Queue) {
              subBuilder.MergeFrom(Queue);
            }
            input.ReadMessage(subBuilder);
            Queue = subBuilder;
            break;
          }
          case 106: {
            global::Nitric.Proto.Resource.v1.TopicResource subBuilder = new global::Nitric.Proto.Resource.v1.TopicResource();
            if (configCase_ == ConfigOneofCase.Topic) {
              subBuilder.MergeFrom(Topic);
            }
            input.ReadMessage(subBuilder);
            Topic = subBuilder;
            break;
          }
          case 114: {
            global::Nitric.Proto.Resource.v1.CollectionResource subBuilder = new global::Nitric.Proto.Resource.v1.CollectionResource();
            if (configCase_ == ConfigOneofCase.Collection) {
              subBuilder.MergeFrom(Collection);
            }
            input.ReadMessage(subBuilder);
            Collection = subBuilder;
            break;
          }
          case 122: {
            global::Nitric.Proto.Resource.v1.SecretResource subBuilder = new global::Nitric.Proto.Resource.v1.SecretResource();
            if (configCase_ == ConfigOneofCase.Secret) {
              subBuilder.MergeFrom(Secret);
            }
            input.ReadMessage(subBuilder);
            Secret = subBuilder;
            break;
          }
          case 130: {
            global::Nitric.Proto.Resource.v1.ApiResource subBuilder = new global::Nitric.Proto.Resource.v1.ApiResource();
            if (configCase_ == ConfigOneofCase.Api) {
              subBuilder.MergeFrom(Api);
            }
            input.ReadMessage(subBuilder);
            Api = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resource_ == null) {
              Resource = new global::Nitric.Proto.Resource.v1.Resource();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 82: {
            global::Nitric.Proto.Resource.v1.PolicyResource subBuilder = new global::Nitric.Proto.Resource.v1.PolicyResource();
            if (configCase_ == ConfigOneofCase.Policy) {
              subBuilder.MergeFrom(Policy);
            }
            input.ReadMessage(subBuilder);
            Policy = subBuilder;
            break;
          }
          case 90: {
            global::Nitric.Proto.Resource.v1.BucketResource subBuilder = new global::Nitric.Proto.Resource.v1.BucketResource();
            if (configCase_ == ConfigOneofCase.Bucket) {
              subBuilder.MergeFrom(Bucket);
            }
            input.ReadMessage(subBuilder);
            Bucket = subBuilder;
            break;
          }
          case 98: {
            global::Nitric.Proto.Resource.v1.QueueResource subBuilder = new global::Nitric.Proto.Resource.v1.QueueResource();
            if (configCase_ == ConfigOneofCase.Queue) {
              subBuilder.MergeFrom(Queue);
            }
            input.ReadMessage(subBuilder);
            Queue = subBuilder;
            break;
          }
          case 106: {
            global::Nitric.Proto.Resource.v1.TopicResource subBuilder = new global::Nitric.Proto.Resource.v1.TopicResource();
            if (configCase_ == ConfigOneofCase.Topic) {
              subBuilder.MergeFrom(Topic);
            }
            input.ReadMessage(subBuilder);
            Topic = subBuilder;
            break;
          }
          case 114: {
            global::Nitric.Proto.Resource.v1.CollectionResource subBuilder = new global::Nitric.Proto.Resource.v1.CollectionResource();
            if (configCase_ == ConfigOneofCase.Collection) {
              subBuilder.MergeFrom(Collection);
            }
            input.ReadMessage(subBuilder);
            Collection = subBuilder;
            break;
          }
          case 122: {
            global::Nitric.Proto.Resource.v1.SecretResource subBuilder = new global::Nitric.Proto.Resource.v1.SecretResource();
            if (configCase_ == ConfigOneofCase.Secret) {
              subBuilder.MergeFrom(Secret);
            }
            input.ReadMessage(subBuilder);
            Secret = subBuilder;
            break;
          }
          case 130: {
            global::Nitric.Proto.Resource.v1.ApiResource subBuilder = new global::Nitric.Proto.Resource.v1.ApiResource();
            if (configCase_ == ConfigOneofCase.Api) {
              subBuilder.MergeFrom(Api);
            }
            input.ReadMessage(subBuilder);
            Api = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BucketResource : pb::IMessage<BucketResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BucketResource> _parser = new pb::MessageParser<BucketResource>(() => new BucketResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BucketResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BucketResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BucketResource(BucketResource other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BucketResource Clone() {
      return new BucketResource(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BucketResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BucketResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BucketResource other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class QueueResource : pb::IMessage<QueueResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueueResource> _parser = new pb::MessageParser<QueueResource>(() => new QueueResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueueResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueueResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueueResource(QueueResource other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueueResource Clone() {
      return new QueueResource(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueueResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueueResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueueResource other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class TopicResource : pb::IMessage<TopicResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TopicResource> _parser = new pb::MessageParser<TopicResource>(() => new TopicResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TopicResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicResource(TopicResource other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicResource Clone() {
      return new TopicResource(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TopicResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TopicResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TopicResource other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class CollectionResource : pb::IMessage<CollectionResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollectionResource> _parser = new pb::MessageParser<CollectionResource>(() => new CollectionResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CollectionResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionResource(CollectionResource other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectionResource Clone() {
      return new CollectionResource(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CollectionResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CollectionResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CollectionResource other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class SecretResource : pb::IMessage<SecretResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SecretResource> _parser = new pb::MessageParser<SecretResource>(() => new SecretResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SecretResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SecretResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SecretResource(SecretResource other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SecretResource Clone() {
      return new SecretResource(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SecretResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SecretResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SecretResource other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// protect your API with JWT authentication
  /// </summary>
  public sealed partial class ApiSecurityDefinitionJwt : pb::IMessage<ApiSecurityDefinitionJwt>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiSecurityDefinitionJwt> _parser = new pb::MessageParser<ApiSecurityDefinitionJwt>(() => new ApiSecurityDefinitionJwt());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ApiSecurityDefinitionJwt> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiSecurityDefinitionJwt() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiSecurityDefinitionJwt(ApiSecurityDefinitionJwt other) : this() {
      issuer_ = other.issuer_;
      audiences_ = other.audiences_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiSecurityDefinitionJwt Clone() {
      return new ApiSecurityDefinitionJwt(this);
    }

    /// <summary>Field number for the "issuer" field.</summary>
    public const int IssuerFieldNumber = 1;
    private string issuer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Issuer {
      get { return issuer_; }
      set {
        issuer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "audiences" field.</summary>
    public const int AudiencesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_audiences_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> audiences_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Audiences {
      get { return audiences_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ApiSecurityDefinitionJwt);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ApiSecurityDefinitionJwt other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Issuer != other.Issuer) return false;
      if(!audiences_.Equals(other.audiences_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Issuer.Length != 0) hash ^= Issuer.GetHashCode();
      hash ^= audiences_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Issuer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Issuer);
      }
      audiences_.WriteTo(output, _repeated_audiences_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Issuer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Issuer);
      }
      audiences_.WriteTo(ref output, _repeated_audiences_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Issuer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Issuer);
      }
      size += audiences_.CalculateSize(_repeated_audiences_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ApiSecurityDefinitionJwt other) {
      if (other == null) {
        return;
      }
      if (other.Issuer.Length != 0) {
        Issuer = other.Issuer;
      }
      audiences_.Add(other.audiences_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Issuer = input.ReadString();
            break;
          }
          case 18: {
            audiences_.AddEntriesFrom(input, _repeated_audiences_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Issuer = input.ReadString();
            break;
          }
          case 18: {
            audiences_.AddEntriesFrom(ref input, _repeated_audiences_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ApiSecurityDefinition : pb::IMessage<ApiSecurityDefinition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiSecurityDefinition> _parser = new pb::MessageParser<ApiSecurityDefinition>(() => new ApiSecurityDefinition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ApiSecurityDefinition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiSecurityDefinition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiSecurityDefinition(ApiSecurityDefinition other) : this() {
      switch (other.DefinitionCase) {
        case DefinitionOneofCase.Jwt:
          Jwt = other.Jwt.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiSecurityDefinition Clone() {
      return new ApiSecurityDefinition(this);
    }

    /// <summary>Field number for the "jwt" field.</summary>
    public const int JwtFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt Jwt {
      get { return definitionCase_ == DefinitionOneofCase.Jwt ? (global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt) definition_ : null; }
      set {
        definition_ = value;
        definitionCase_ = value == null ? DefinitionOneofCase.None : DefinitionOneofCase.Jwt;
      }
    }

    private object definition_;
    /// <summary>Enum of possible cases for the "definition" oneof.</summary>
    public enum DefinitionOneofCase {
      None = 0,
      Jwt = 1,
    }
    private DefinitionOneofCase definitionCase_ = DefinitionOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DefinitionOneofCase DefinitionCase {
      get { return definitionCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDefinition() {
      definitionCase_ = DefinitionOneofCase.None;
      definition_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ApiSecurityDefinition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ApiSecurityDefinition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Jwt, other.Jwt)) return false;
      if (DefinitionCase != other.DefinitionCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (definitionCase_ == DefinitionOneofCase.Jwt) hash ^= Jwt.GetHashCode();
      hash ^= (int) definitionCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (definitionCase_ == DefinitionOneofCase.Jwt) {
        output.WriteRawTag(10);
        output.WriteMessage(Jwt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (definitionCase_ == DefinitionOneofCase.Jwt) {
        output.WriteRawTag(10);
        output.WriteMessage(Jwt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (definitionCase_ == DefinitionOneofCase.Jwt) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Jwt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ApiSecurityDefinition other) {
      if (other == null) {
        return;
      }
      switch (other.DefinitionCase) {
        case DefinitionOneofCase.Jwt:
          if (Jwt == null) {
            Jwt = new global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt();
          }
          Jwt.MergeFrom(other.Jwt);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt subBuilder = new global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt();
            if (definitionCase_ == DefinitionOneofCase.Jwt) {
              subBuilder.MergeFrom(Jwt);
            }
            input.ReadMessage(subBuilder);
            Jwt = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt subBuilder = new global::Nitric.Proto.Resource.v1.ApiSecurityDefinitionJwt();
            if (definitionCase_ == DefinitionOneofCase.Jwt) {
              subBuilder.MergeFrom(Jwt);
            }
            input.ReadMessage(subBuilder);
            Jwt = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ApiScopes : pb::IMessage<ApiScopes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiScopes> _parser = new pb::MessageParser<ApiScopes>(() => new ApiScopes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ApiScopes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiScopes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiScopes(ApiScopes other) : this() {
      scopes_ = other.scopes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiScopes Clone() {
      return new ApiScopes(this);
    }

    /// <summary>Field number for the "scopes" field.</summary>
    public const int ScopesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_scopes_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> scopes_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Scopes {
      get { return scopes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ApiScopes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ApiScopes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!scopes_.Equals(other.scopes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= scopes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      scopes_.WriteTo(output, _repeated_scopes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      scopes_.WriteTo(ref output, _repeated_scopes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += scopes_.CalculateSize(_repeated_scopes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ApiScopes other) {
      if (other == null) {
        return;
      }
      scopes_.Add(other.scopes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            scopes_.AddEntriesFrom(input, _repeated_scopes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            scopes_.AddEntriesFrom(ref input, _repeated_scopes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ApiResource : pb::IMessage<ApiResource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiResource> _parser = new pb::MessageParser<ApiResource>(() => new ApiResource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ApiResource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiResource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiResource(ApiResource other) : this() {
      securityDefinitions_ = other.securityDefinitions_.Clone();
      security_ = other.security_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApiResource Clone() {
      return new ApiResource(this);
    }

    /// <summary>Field number for the "security_definitions" field.</summary>
    public const int SecurityDefinitionsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiSecurityDefinition>.Codec _map_securityDefinitions_codec
        = new pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiSecurityDefinition>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Nitric.Proto.Resource.v1.ApiSecurityDefinition.Parser), 10);
    private readonly pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiSecurityDefinition> securityDefinitions_ = new pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiSecurityDefinition>();
    /// <summary>
    /// Security definitions for the api
    /// These may be used by registered routes and operations on the API
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiSecurityDefinition> SecurityDefinitions {
      get { return securityDefinitions_; }
    }

    /// <summary>Field number for the "security" field.</summary>
    public const int SecurityFieldNumber = 2;
    private static readonly pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiScopes>.Codec _map_security_codec
        = new pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiScopes>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Nitric.Proto.Resource.v1.ApiScopes.Parser), 18);
    private readonly pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiScopes> security_ = new pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiScopes>();
    /// <summary>
    /// root level security for this api
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::Nitric.Proto.Resource.v1.ApiScopes> Security {
      get { return security_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ApiResource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ApiResource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!SecurityDefinitions.Equals(other.SecurityDefinitions)) return false;
      if (!Security.Equals(other.Security)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= SecurityDefinitions.GetHashCode();
      hash ^= Security.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      securityDefinitions_.WriteTo(output, _map_securityDefinitions_codec);
      security_.WriteTo(output, _map_security_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      securityDefinitions_.WriteTo(ref output, _map_securityDefinitions_codec);
      security_.WriteTo(ref output, _map_security_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += securityDefinitions_.CalculateSize(_map_securityDefinitions_codec);
      size += security_.CalculateSize(_map_security_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ApiResource other) {
      if (other == null) {
        return;
      }
      securityDefinitions_.Add(other.securityDefinitions_);
      security_.Add(other.security_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            securityDefinitions_.AddEntriesFrom(input, _map_securityDefinitions_codec);
            break;
          }
          case 18: {
            security_.AddEntriesFrom(input, _map_security_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            securityDefinitions_.AddEntriesFrom(ref input, _map_securityDefinitions_codec);
            break;
          }
          case 18: {
            security_.AddEntriesFrom(ref input, _map_security_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ResourceDeclareResponse : pb::IMessage<ResourceDeclareResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceDeclareResponse> _parser = new pb::MessageParser<ResourceDeclareResponse>(() => new ResourceDeclareResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResourceDeclareResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nitric.Proto.Resource.v1.ResourceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceDeclareResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceDeclareResponse(ResourceDeclareResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceDeclareResponse Clone() {
      return new ResourceDeclareResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResourceDeclareResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResourceDeclareResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResourceDeclareResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
