// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nitric/proto/sql/v1/sql.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nitric.Proto.Sql.v1 {
  /// <summary>
  /// The Nitric Secret Service
  /// </summary>
  public static partial class Sql
  {
    static readonly string __ServiceName = "nitric.proto.sql.v1.Sql";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest> __Marshaller_nitric_proto_sql_v1_SqlConnectionStringRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse> __Marshaller_nitric_proto_sql_v1_SqlConnectionStringResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse.Parser));

    static readonly grpc::Method<global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest, global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse> __Method_ConnectionString = new grpc::Method<global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest, global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ConnectionString",
        __Marshaller_nitric_proto_sql_v1_SqlConnectionStringRequest,
        __Marshaller_nitric_proto_sql_v1_SqlConnectionStringResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nitric.Proto.Sql.v1.SqlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Sql</summary>
    [grpc::BindServiceMethod(typeof(Sql), "BindService")]
    public abstract partial class SqlBase
    {
      /// <summary>
      /// Retrieve the connection string for a given database
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse> ConnectionString(global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Sql</summary>
    public partial class SqlClient : grpc::ClientBase<SqlClient>
    {
      /// <summary>Creates a new client for Sql</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SqlClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Sql that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SqlClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SqlClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SqlClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Retrieve the connection string for a given database
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse ConnectionString(global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectionString(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve the connection string for a given database
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse ConnectionString(global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ConnectionString, null, options, request);
      }
      /// <summary>
      /// Retrieve the connection string for a given database
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse> ConnectionStringAsync(global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectionStringAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve the connection string for a given database
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse> ConnectionStringAsync(global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ConnectionString, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SqlClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SqlClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SqlBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ConnectionString, serviceImpl.ConnectionString).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SqlBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ConnectionString, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.Sql.v1.SqlConnectionStringRequest, global::Nitric.Proto.Sql.v1.SqlConnectionStringResponse>(serviceImpl.ConnectionString));
    }

  }
}
#endregion
