// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/websocket/v1/websocket.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nitric.Proto.Websocket.v1 {
  public static partial class WebsocketService
  {
    static readonly string __ServiceName = "nitric.websocket.v1.WebsocketService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Nitric.Proto.Websocket.v1.WebsocketSendRequest> __Marshaller_nitric_websocket_v1_WebsocketSendRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Websocket.v1.WebsocketSendRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.Websocket.v1.WebsocketSendResponse> __Marshaller_nitric_websocket_v1_WebsocketSendResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Websocket.v1.WebsocketSendResponse.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest> __Marshaller_nitric_websocket_v1_WebsocketCloseRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest.Parser));
    static readonly grpc::Marshaller<global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse> __Marshaller_nitric_websocket_v1_WebsocketCloseResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse.Parser));

    static readonly grpc::Method<global::Nitric.Proto.Websocket.v1.WebsocketSendRequest, global::Nitric.Proto.Websocket.v1.WebsocketSendResponse> __Method_Send = new grpc::Method<global::Nitric.Proto.Websocket.v1.WebsocketSendRequest, global::Nitric.Proto.Websocket.v1.WebsocketSendResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_nitric_websocket_v1_WebsocketSendRequest,
        __Marshaller_nitric_websocket_v1_WebsocketSendResponse);

    static readonly grpc::Method<global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest, global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse> __Method_Close = new grpc::Method<global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest, global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Close",
        __Marshaller_nitric_websocket_v1_WebsocketCloseRequest,
        __Marshaller_nitric_websocket_v1_WebsocketCloseResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nitric.Proto.Websocket.v1.WebsocketReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WebsocketService</summary>
    [grpc::BindServiceMethod(typeof(WebsocketService), "BindService")]
    public abstract partial class WebsocketServiceBase
    {
      /// <summary>
      /// Send a messages to a websocket
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.Websocket.v1.WebsocketSendResponse> Send(global::Nitric.Proto.Websocket.v1.WebsocketSendRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Close a websocket connection
      /// This can be used to force a client to disconnect
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse> Close(global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WebsocketService</summary>
    public partial class WebsocketServiceClient : grpc::ClientBase<WebsocketServiceClient>
    {
      /// <summary>Creates a new client for WebsocketService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WebsocketServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WebsocketService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WebsocketServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WebsocketServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WebsocketServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Send a messages to a websocket
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Websocket.v1.WebsocketSendResponse Send(global::Nitric.Proto.Websocket.v1.WebsocketSendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Send a messages to a websocket
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Websocket.v1.WebsocketSendResponse Send(global::Nitric.Proto.Websocket.v1.WebsocketSendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      /// <summary>
      /// Send a messages to a websocket
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Websocket.v1.WebsocketSendResponse> SendAsync(global::Nitric.Proto.Websocket.v1.WebsocketSendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Send a messages to a websocket
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Websocket.v1.WebsocketSendResponse> SendAsync(global::Nitric.Proto.Websocket.v1.WebsocketSendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      /// <summary>
      /// Close a websocket connection
      /// This can be used to force a client to disconnect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse Close(global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Close(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Close a websocket connection
      /// This can be used to force a client to disconnect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse Close(global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Close, null, options, request);
      }
      /// <summary>
      /// Close a websocket connection
      /// This can be used to force a client to disconnect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse> CloseAsync(global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CloseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Close a websocket connection
      /// This can be used to force a client to disconnect
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse> CloseAsync(global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Close, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WebsocketServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WebsocketServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WebsocketServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send)
          .AddMethod(__Method_Close, serviceImpl.Close).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WebsocketServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Send, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.Websocket.v1.WebsocketSendRequest, global::Nitric.Proto.Websocket.v1.WebsocketSendResponse>(serviceImpl.Send));
      serviceBinder.AddMethod(__Method_Close, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nitric.Proto.Websocket.v1.WebsocketCloseRequest, global::Nitric.Proto.Websocket.v1.WebsocketCloseResponse>(serviceImpl.Close));
    }

  }
}
#endregion
