name: dotnet Build and Test

on: pull_request

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.SUB_MODULE_PAT}}
        submodules: recursive
    - name: Check License Headers
      run: npx license-check-and-add check -f ./tools/license/licenseconfig.json
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.SUB_MODULE_PAT}}
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Find and Replace Version templates
      run: |
        sed -i.bak 's/${VERSION}/0.0.1/g' Nitric.Sdk/Nitric.Sdk.csproj
        sed -i.bak 's/${VERSION}/0.0.1/g' Nitric.Proto/Nitric.Proto.csproj
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Check Dependency Licensing
      run: |
        dotnet tool install --global dotnet-project-licenses
        echo "['MIT','Apache-2.0','BSD-3-Clause']" > licenses.json
        echo "['Google.Protobuf']" > filter.json
        dotnet-project-licenses -i Nitric.Sdk --allowed-license-types licenses.json --packages-filter filter.json
        rm licenses.json
        rm filter.json
        dotnet tool uninstall --global dotnet-project-licenses

