name: Bump Package Versions, Tag and Draft Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get latest tag
      run: |
        echo "::set-output name=TAG_REF::`git describe --abbrev=0`"
      id: latest_tag
    - name: Find and Replace Version templates
      run: |
        sed -i.bak 's/${VERSION}/0.0.1/g' Nitric.Sdk/Nitric.Sdk.csproj
        sed -i.bak 's/${VERSION}/0.0.1/g' Nitric.Proto/Nitric.Proto.csproj
    - name: Install Dependencies
      run: dotnet restore

    - name: Push version bump & tags
      run: |
        git fetch
        git checkout main
        git push origin main --follow-tags

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.latest_tag.outputs.TAG_REF }}
        release_name: Release ${{ steps.latest_tag.outputs.TAG_REF }}
        body: See CHANGELOG.md for changes
        draft: true
        prerelease: false