name: Bump Package Versions, Tag and Draft Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  version:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Install Versionize
      run: dotnet tool install --global Versionize --version 1.6.2

    - name: Install Dependencies
      run: dotnet restore
    
    - name: Version Bump and tag
      run: |
        versionize --skip-commit -w  ./Nitric.Proto
        versionize -w ./Nitric.Sdk
      shell: bash

    - name: Push version bump & tags
      run: |
        git fetch
        git checkout main
        git push origin main --follow-tags

    - name: Get latest tag
      run: |
        echo "::set-output name=TAG_REF::`git describe --abbrev=0`"
      id: latest_tag
      
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.latest_tag.outputs.TAG_REF }}
        release_name: Release ${{ steps.latest_tag.outputs.TAG_REF }}
        body: See CHANGELOG.md for changes
        draft: true
        prerelease: false