name: Publish on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
        nuget-version: '5.x'
    - name: Install Dependencies
      run: nuget restore Nitric.Sdk.csproj
    - name: Publish
      run: |
        cd Nitric.Sdk
        mkdir __out
        nuget pack Nitric.Sdk.csproj -c Release -o __out --no-restore -IncludeReferencedProjects
        nuget setApiKey ${{ secrets.NUGET_TOKEN }}
        nuget push "./__out/*.nupkg" -Source https://api.nuget.org/v3/index.json
        rm -rf __out
